services:
  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis_2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rate-limiter-network

  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: rate-limiter-api_v2
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - rate-db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rate-limiter-network

  rate-db:
    image: postgres:15
    container_name: rate-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rate-limiter-network
volumes:
  redis_data:
  postgres_data:
networks:
  rate-limiter-network:
    driver: bridge